#!/usr/bin/env bash
set -euo pipefail

# Generate the four held-out Organization choice-probe targets used by the
# transfer matrix.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCENARIO_DIR="${SCENARIO_DIR:-$REPO_ROOT/data/bfi2c_organization/scenarios/test}"
SCRIPT="$SCRIPT_DIR/generate_choice_probes.py"
CONFIG="${CONFIG:-bfi2c_organization}"
COUNT="${COUNT:-40}"
MODEL="${MODEL:-claude-opus-4-6}"
PER_ITEM="${PER_ITEM:-10}"
BATCH_SIZE="${BATCH_SIZE:-5}"

mkdir -p "$SCENARIO_DIR"

python "$SCRIPT" \
  --config "$CONFIG" \
  --register fp \
  --all-items \
  --n "$PER_ITEM" \
  --model "$MODEL" \
  --out "$SCENARIO_DIR/choice_fp.json"

python "$SCRIPT" \
  --config "$CONFIG" \
  --register task \
  --all-items \
  --n "$COUNT" \
  --batch-size "$BATCH_SIZE" \
  --model "$MODEL" \
  --out "$SCENARIO_DIR/choice_task.json"

# Advice-task/workflow: advice scenarios generated by the pipeline, not derived
# from original questionnaire daily situations.
python "$SCRIPT" \
  --config "$CONFIG" \
  --register advice \
  --all-items \
  --n "$COUNT" \
  --batch-size "$BATCH_SIZE" \
  --model "$MODEL" \
  --out "$SCENARIO_DIR/choice_advice_task.json"

# Advice-daily: generated from the original BFI item anchors, like FP, but in an
# advice-seeking daily-life register.
python "$SCRIPT" \
  --config "$CONFIG" \
  --register advice_daily \
  --all-items \
  --n "$PER_ITEM" \
  --model "$MODEL" \
  --out "$SCENARIO_DIR/choice_advice_daily.json"

echo "Generated choice suite in $SCENARIO_DIR"
